name: build
on:
  push:
    paths:
      - ./flowchart.puml
    branches: [ main ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]

#env:
#  aaa: bbb

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: .
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
